config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token
from llm_on_web.users.views import user_contact_view

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    path("chat/", include("llm_on_web.chat.urls"), name="chat"),
    path(
        "contact/",
        view=user_contact_view,
        name="contact",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("llm_on_web.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

llm_on_web/chat/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import llava_chat_view
from .views import user_chat_view

app_name = "chat"
urlpatterns = [
    path("", view=user_chat_view, name="chat"),
    path(
        "llava/",
        view=llava_chat_view,
        name="llava",
    ),
    path(
        "llava/conversations/",
        TemplateView.as_view(template_name="pages/chat_llava.html"),
        name="llava_conversation",
    ),
]

llm_on_web/users/urls.py
from django.urls import path

from .views import user_conversations_detailed_view
from .views import user_conversations_view
from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
    path("<int:pk>/conversations/", view=user_conversations_view, name="conversations"),
    path(
        "conversations/<uuid:conversationid>/",
        view=user_conversations_detailed_view,
        name="conversation_detail",
    ),
]

llm_on_web/chat/models.py
import uuid

from django.db import models

from llm_on_web.users.models import User


class Chatid(models.Model):
    chatid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    chat_title = models.CharField(max_length=255, default="", blank=True)
    userid = models.ForeignKey(User, on_delete=models.RESTRICT, null=True)

    def __str__(self):
        return f"Chats: {self.userid}"


class Conversations(models.Model):
    conversationid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    chatid = models.ForeignKey(
        Chatid,
        on_delete=models.CASCADE,
        related_name="conversations",
    )
    userid = models.ForeignKey(User, on_delete=models.RESTRICT)
    llm_response = models.TextField(max_length=1000, default="", blank=True)
    user_query = models.TextField(default="")
    imagequery = models.ImageField(
        upload_to="user-images-query/",
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (
            f"Conversation {self.conversationid} in chat {self.chatid} by {self.userid}"
        )

llm_on_web/users/models.py
from typing import ClassVar

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import CharField
from django.db.models import EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .managers import UserManager


class User(AbstractUser):
    """
    Default custom user model for llm_on_web.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore[assignment]
    last_name = None  # type: ignore[assignment]
    email = EmailField(_("email address"), unique=True)
    username = None  # type: ignore[assignment]
    userpicture = models.ImageField(upload_to="user_pictures/", blank=True, null=True)
    currentchatid = models.CharField(default="", blank=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects: ClassVar[UserManager] = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

llm_on_web/chat/forms.py
from llm_on_web.chat.models import Conversations


class UserConversationForm:
    class Meta:
        model = Conversations
        fields = ["userid", "user_query", "imagequery"]

llm_on_web/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django import forms
from django.contrib.auth import forms as admin_forms
from django.core.validators import EmailValidator
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):  # type: ignore[name-defined]
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):  # type: ignore[name-defined]
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["name", "email", "userpicture"]


class UserContactForm(forms.Form):
    email = forms.CharField(validators=[EmailValidator()])
    subject = forms.CharField(max_length=255)
    message = forms.CharField(widget=forms.Textarea)

llm_on_web/chat/views.py
from datetime import datetime

import pytz
from django.shortcuts import render
from django.views.generic import TemplateView

from llm_on_web.users.models import User

from .models import Chatid


class ChatMixin:
    def handle_authenticated_user(self, request):
        current_user = User.objects.get(pk=request.user.pk)
        chat_title = str(datetime.now(pytz.utc))
        newchat = Chatid.objects.create(chat_title=chat_title)
        newchat.userid = current_user
        newchat.save()
        current_chat_id = newchat.chatid
        current_user.currentchatid = current_chat_id
        current_user.save()


class ChatView(ChatMixin, TemplateView):
    template_name = "pages/chat.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.handle_authenticated_user(request)
        return render(request, self.template_name)


user_chat_view = ChatView.as_view()


class LlavaChatView(ChatMixin, TemplateView):
    template_name = "pages/chat_llava.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.handle_authenticated_user(request)
        return render(request, self.template_name)


llava_chat_view = LlavaChatView.as_view()

llm_on_web/users/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin
from rest_framework.mixins import RetrieveModelMixin
from rest_framework.mixins import UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from llm_on_web.users.models import User

from .serializers import UserSerializer


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "pk"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

llm_on_web/users/views.py
# ruff: noqa: E501

from allauth.account.models import EmailAddress
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import EmailMessage
from django.core.mail import get_connection
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import FormView
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.views.generic import UpdateView

from config.settings.local import RESEND_API_KEY
from config.settings.local import RESEND_SMTP_HOST
from config.settings.local import RESEND_SMTP_PORT
from config.settings.local import RESEND_SMTP_USERNAME
from llm_on_web.chat.models import Chatid
from llm_on_web.chat.models import Conversations
from llm_on_web.users.forms import UserContactForm
from llm_on_web.users.forms import UserUpdateForm
from llm_on_web.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = UserUpdateForm
    template_name = "users/user_form.html"
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        response = super().form_valid(form)
        new_email = form.cleaned_data.get("email")
        email_address = EmailAddress.objects.filter(user=self.object).first()
        if email_address:
            email_address.email = new_email
            email_address.save()
        else:
            EmailAddress.objects.create(
                user=self.object,
                email=new_email,
                verified=True,
                primary=True,
            )
        return response


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()


class UserConversationsView(LoginRequiredMixin, TemplateView):
    template_name = "users/conversations.html"

    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=request.user.pk)
        user_chats = Chatid.objects.filter(userid=user)
        conversations_with_chatid = (
            Conversations.objects.filter(chatid__in=user_chats)
            .select_related("chatid")
            .all()
        )
        unique_chatids = {
            conversation.chatid for conversation in conversations_with_chatid
        }
        context = {"chats": unique_chatids}
        return render(request, template_name=self.template_name, context=context)


user_conversations_view = UserConversationsView.as_view()


class UserConversationsDetailedView(LoginRequiredMixin, TemplateView):
    template_name = "users/conversations_detailed.html"  # corrected the conversations

    def get(self, request, *args, **kwargs):
        queridtid = kwargs.get("conversationid")
        chatid = get_object_or_404(Chatid, chatid=queridtid)
        user_conversations = Conversations.objects.filter(chatid=chatid)
        context = {"user_conversations": user_conversations}
        return self.render_to_response(context)


user_conversations_detailed_view = UserConversationsDetailedView.as_view()


class UserContactView(LoginRequiredMixin, FormView):
    template_name = "pages/contact.html"
    form_class = UserContactForm
    success_url = "/contact"

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        subject = form.cleaned_data["subject"]
        message = form.cleaned_data["message"]
        from_email = "gemma_support@appsupport.shukla.ru"
        body1 = "Thank you for contacting us"
        body2 = f"we got the following message: {message}"

        if form.is_valid():
            with get_connection(
                host=RESEND_SMTP_HOST,
                port=RESEND_SMTP_PORT,
                username=RESEND_SMTP_USERNAME,
                password=RESEND_API_KEY,
                use_tls=True,
            ) as connection:
                EmailMessage(
                    subject=subject,
                    body=body1 + body2,
                    to=[email],
                    from_email=from_email,
                    connection=connection,
                ).send(fail_silently=False)

            return super().form_valid(form)

        return redirect("contact")


user_contact_view = UserContactView.as_view()

llm_on_web/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}
  Forbidden (403)
{% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

llm_on_web/templates/base.html
{% load static i18n %}
{% load static %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" />
    <title>
      {% block title %}
      {% endblock title %}
      | Gemma
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Web app to interact with LLM locally" />
    <meta name="author" content="Rituparn Shukla" />
    <link rel="icon" href="{% static 'images/favicons/gemini-icon.png' %}" />
    {% block css %}
      <link href="{% static 'css/output.css' %}" rel="stylesheet" />
    {% endblock css %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Your stuff: Third-party javascript libraries go here -->
      <!-- place project specific Javascript in this file -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/Flip.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/ScrollTrigger.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/Observer.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/ScrollToPlugin.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/Draggable.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/MotionPathPlugin.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/EaselPlugin.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/PixiPlugin.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/TextPlugin.min.js"></script>
      <!-- RoughEase, ExpoScaleEase and SlowMo are all included in the EasePack file -->
      <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/EasePack.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/CustomEase.min.js"></script>
    {% endblock javascript %}
  </head>
  <body class="{% block bodyclass %}{% endblock bodyclass %}  ">
    {% block body %}
      <nav class=" z-50 bg-gray-900 backdrop-blur-sm bg-opacity-70 top-1 rounded-b-[2.5rem] fixed w-full  font-sans1 ">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
          <a href="{% url 'home' %}"
             class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="{% static 'images/favicons/gemini-icon.png' %}"
                 class="h-8"
                 alt="Gemma" />
            <span class="self-center text-2xl font-semibold whitespace-nowrap text-white">Gemma</span>
          </a>
          <div class="flex items-center  mx-4 md:order-2 space-x-3 md:space-x-0 space-x-reverse">
            <button type="button"
                    class="flex text-sm bg-gray-800 rounded-full  focus:ring-4 focus:ring-gray-300"
                    id="user-menu-button"
                    aria-expanded="false"
                    data-dropdown-toggle="user-dropdown"
                    data-dropdown-placement="bottom">
              <span class="sr-only">Open user menu</span>
              <img class="w-8 h-8 rounded-full"
                   src="{% if request.user.userpicture %}/media/{{ request.user.userpicture }}{% else %}{% static 'images/user2.svg' %}{% endif %}"
                   alt="User Picture" />
            </button>
            <div class=" hidden my-4 rounded-xl font-sans1 divide-y divide-gray-100 rounded-lg shadow-xl bg-gray-900 backdrop-blur-xl bg-opacity-60"
                 id="user-dropdown">
              <div class="px-4 py-3">
                {% if request.user.is_authenticated %}
                  <span class="block text-sm text-white">{{ request.user.name }}</span>
                  <span class="block text-sm text-gray-100">{{ request.user.email }}</span>
                {% else %}
                  <span class="block text-sm text-white text-center">Hello, please sign in!</span>
                {% endif %}
              </div>
              <ul class="py-2" aria-labelledby="user-menu-button">
                {% if request.user.is_authenticated %}
                  <li>
                    <a href="{% url 'users:detail' request.user.pk %}"
                       class="block px-4 py-2 text-sm text-center text-gray-700  hover:bg-gray-600 dark:text-gray-200 text-white">{% translate "My Profile" %}</a>
                  </li>
                  <li class="md:hidden">
                    <a href="{% url 'chat:chat' %}"
                       class="block px-4 py-2 text-sm text-center text-gray-700  hover:bg-gray-600 dark:text-gray-200 text-white">Chat</a>
                  </li>
                  <li>
                    <a href="{% url 'users:conversations' request.user.pk %}"
                       class="block px-4 py-2 text-center text-sm text-gray-700 hover:bg-gray-600 text-white">Conversations</a>
                  </li>
                  <li class="md:hidden">
                    <a href="{% url 'contact' %}"
                       class="block px-4 py-2 text-sm text-center text-gray-700  hover:bg-gray-600 dark:text-gray-200 text-white">Contact</a>
                  </li>
                  <li class="md:hidden">
                    <a href="{% url 'about' %}"
                       class="block px-4 py-2 text-sm text-center text-gray-700  hover:bg-gray-600 dark:text-gray-200 text-white">About</a>
                  </li>
                  <li>
                    <a href="{% url 'account_logout' %}"
                       class="block px-4 py-2 text-center text-sm text-gray-700 hover:bg-gray-600  text-white">{% translate "Sign Out" %}</a>
                  </li>
                {% else %}
                  {% if ACCOUNT_ALLOW_REGISTRATION %}
                    <li>
                      <a id="sign-up-link"
                         href="{% url 'account_signup' %}"
                         class="block px-4 py-2 text-center text-sm text-gray-700 hover:bg-gray-600 dark:text-gray-200 text-white">{% translate "Sign Up" %}</a>
                    </li>
                  {% endif %}
                  <li>
                    <a id="log-in-link"
                       href="{% url 'account_login' %}"
                       class="block px-4 py-2 text-center text-sm text-gray-700 hover:bg-gray-600 dark:text-gray-200 text-white">{% translate "Sign In" %}</a>
                  </li>
		   <li class="md:hidden">
                    <a href="{% url 'chat:chat' %}"
                       class="block px-4 py-2 text-sm text-center text-gray-700  hover:bg-gray-600 dark:text-gray-200 text-white">Chat</a>
                  </li>
                  <li class="md:hidden">
                    <a href="{% url 'about' %}"
                       class="block px-4 py-2 text-sm text-center text-gray-700  hover:bg-gray-600 dark:text-gray-200 text-white">About</a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
          <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1"
               id="navbar-site">
            <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border  rounded-lg  md:space-x-16  md:flex-row md:mt-0 md:border-0">
              <li>
                <a href="{% url 'home' %}"
                   class="block py-2 px-3 text-white bg-gray-100 rounded md:bg-transparent md:p-0 hover:text-cyan-300"
                   aria-current="page">Home</a>
              </li>
              <li>
                <a href="{% url 'about' %}"
                   class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent hover:text-cyan-300 md:p-0 text-white  hover:bg-gray-700 hover:text-white md:hover:bg-transparent border-gray-700">About</a>
              </li>
              <li>
                <a href="{% url 'chat:chat' %}"
                   class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent hover:text-cyan-300 md:p-0 text-white  hover:bg-gray-700 hover:text-white md:hover:bg-transparent border-gray-700">Chat</a>
              </li>
              <li>
                <a href="{% url 'contact' %}"
                   class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent  hover:text-cyan-300 md:p-0 text-white  hover:bg-gray-700 hover:text-white md:hover:bg-transparent border-gray-700">Contact</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      {% block main %}
        {% block content %}
        {% endblock content %}
      {% endblock main %}
    {% endblock body %}
    {% block modal %}
    {% endblock modal %}
    {% block inline_javascript %}
    {% endblock inline_javascript %}
  </body>
</html>