config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token
from llm_on_web.users.views import user_contact_view

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    path("chat/", include("llm_on_web.chat.urls"), name="chat"),
    path(
        "contact/",
        view=user_contact_view,
        name="contact",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("llm_on_web.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

llm_on_web/chat/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import llava_chat_view
from .views import user_chat_view

app_name = "chat"
urlpatterns = [
    path("", view=user_chat_view, name="chat"),
    path(
        "llava/",
        view=llava_chat_view,
        name="llava",
    ),
    path(
        "llava/conversations/",
        TemplateView.as_view(template_name="pages/chat_llava.html"),
        name="llava_conversation",
    ),
]

llm_on_web/users/urls.py
from django.urls import path

from .views import user_conversations_detailed_view
from .views import user_conversations_view
from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
    path("<int:pk>/conversations/", view=user_conversations_view, name="conversations"),
    path(
        "conversations/<uuid:conversationid>/",
        view=user_conversations_detailed_view,
        name="conversation_detail",
    ),
]

llm_on_web/chat/models.py
import uuid

from django.db import models

from llm_on_web.users.models import User


class Chatid(models.Model):
    chatid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    chat_title = models.CharField(max_length=255, default="", blank=True)
    userid = models.ForeignKey(User, on_delete=models.RESTRICT, null=True)

    def __str__(self):
        return f"Chats: {self.userid}"


class Conversations(models.Model):
    conversationid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    chatid = models.ForeignKey(
        Chatid,
        on_delete=models.CASCADE,
        related_name="conversations",
    )
    userid = models.ForeignKey(User, on_delete=models.RESTRICT)
    llm_response = models.TextField(max_length=1000, default="", blank=True)
    user_query = models.TextField(default="")
    imagequery = models.ImageField(
        upload_to="user-images-query/",
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (
            f"Conversation {self.conversationid} in chat {self.chatid} by {self.userid}"
        )

llm_on_web/users/models.py
from typing import ClassVar

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import CharField
from django.db.models import EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .managers import UserManager


class User(AbstractUser):
    """
    Default custom user model for llm_on_web.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore[assignment]
    last_name = None  # type: ignore[assignment]
    email = EmailField(_("email address"), unique=True)
    username = None  # type: ignore[assignment]
    userpicture = models.ImageField(upload_to="user_pictures/", blank=True, null=True)
    currentchatid = models.CharField(default="", blank=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects: ClassVar[UserManager] = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

llm_on_web/chat/forms.py
from llm_on_web.chat.models import Conversations


class UserConversationForm:
    class Meta:
        model = Conversations
        fields = ["userid", "user_query", "imagequery"]

llm_on_web/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django import forms
from django.contrib.auth import forms as admin_forms
from django.core.validators import EmailValidator
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):  # type: ignore[name-defined]
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):  # type: ignore[name-defined]
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["name", "email", "userpicture"]


class UserContactForm(forms.Form):
    email = forms.CharField(validators=[EmailValidator()])
    subject = forms.CharField(max_length=255)
    message = forms.CharField(widget=forms.Textarea)

llm_on_web/chat/views.py
from datetime import datetime

import pytz
from django.shortcuts import render
from django.views.generic import TemplateView

from llm_on_web.users.models import User

from .models import Chatid


class ChatMixin:
    def handle_authenticated_user(self, request):
        current_user = User.objects.get(pk=request.user.pk)
        chat_title = str(datetime.now(pytz.utc))
        newchat = Chatid.objects.create(chat_title=chat_title)
        newchat.userid = current_user
        newchat.save()
        current_chat_id = newchat.chatid
        current_user.currentchatid = current_chat_id
        current_user.save()


class ChatView(ChatMixin, TemplateView):
    template_name = "pages/chat.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.handle_authenticated_user(request)
        return render(request, self.template_name)


user_chat_view = ChatView.as_view()


class LlavaChatView(ChatMixin, TemplateView):
    template_name = "pages/chat_llava.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.handle_authenticated_user(request)
        return render(request, self.template_name)


llava_chat_view = LlavaChatView.as_view()

llm_on_web/users/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin
from rest_framework.mixins import RetrieveModelMixin
from rest_framework.mixins import UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from llm_on_web.users.models import User

from .serializers import UserSerializer


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "pk"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

llm_on_web/users/views.py
# ruff: noqa: E501

from allauth.account.models import EmailAddress
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import EmailMessage
from django.core.mail import get_connection
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import FormView
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.views.generic import UpdateView

from config.settings.local import RESEND_API_KEY
from config.settings.local import RESEND_SMTP_HOST
from config.settings.local import RESEND_SMTP_PORT
from config.settings.local import RESEND_SMTP_USERNAME
from llm_on_web.chat.models import Chatid
from llm_on_web.chat.models import Conversations
from llm_on_web.users.forms import UserContactForm
from llm_on_web.users.forms import UserUpdateForm
from llm_on_web.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = UserUpdateForm
    template_name = "users/user_form.html"
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        response = super().form_valid(form)
        new_email = form.cleaned_data.get("email")
        email_address = EmailAddress.objects.filter(user=self.object).first()
        if email_address:
            email_address.email = new_email
            email_address.save()
        else:
            EmailAddress.objects.create(
                user=self.object,
                email=new_email,
                verified=True,
                primary=True,
            )
        return response


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()


class UserConversationsView(LoginRequiredMixin, TemplateView):
    template_name = "users/conversations.html"

    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=request.user.pk)
        user_chats = Chatid.objects.filter(userid=user)
        conversations_with_chatid = (
            Conversations.objects.filter(chatid__in=user_chats)
            .select_related("chatid")
            .all()
        )
        unique_chatids = {
            conversation.chatid for conversation in conversations_with_chatid
        }
        context = {"chats": unique_chatids}
        return render(request, template_name=self.template_name, context=context)


user_conversations_view = UserConversationsView.as_view()


class UserConversationsDetailedView(LoginRequiredMixin, TemplateView):
    template_name = "users/conversations_detailed.html"  # corrected the conversations

    def get(self, request, *args, **kwargs):
        queridtid = kwargs.get("conversationid")
        chatid = get_object_or_404(Chatid, chatid=queridtid)
        user_conversations = Conversations.objects.filter(chatid=chatid)
        context = {"user_conversations": user_conversations}
        return self.render_to_response(context)


user_conversations_detailed_view = UserConversationsDetailedView.as_view()


class UserContactView(LoginRequiredMixin, FormView):
    template_name = "pages/contact.html"
    form_class = UserContactForm
    success_url = "/contact"

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        subject = form.cleaned_data["subject"]
        message = form.cleaned_data["message"]
        from_email = "gemma_support@appsupport.shukla.ru"
        body1 = "Thank you for contacting us"
        body2 = f"we got the following message: {message}"

        if form.is_valid():
            with get_connection(
                host=RESEND_SMTP_HOST,
                port=RESEND_SMTP_PORT,
                username=RESEND_SMTP_USERNAME,
                password=RESEND_API_KEY,
                use_tls=True,
            ) as connection:
                EmailMessage(
                    subject=subject,
                    body=body1 + body2,
                    to=[email],
                    from_email=from_email,
                    connection=connection,
                ).send(fail_silently=False)

            return super().form_valid(form)

        return redirect("contact")


user_contact_view = UserContactView.as_view()

llm_on_web/templates/users/conversations.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  Conversations
{% endblock title %}
{% block bodyclass %}
  bg-gemma bg-cover bg-no-repeat min-h-screen overflow-hidden
{% endblock bodyclass %}
{% block javascript %}
  {{ block.super }}
  <script src="{% static 'js/chat-handle.js' %}"></script>
{% endblock javascript %}
{% block content %}
  <div class="h-custom-vh w-full mt-20 px-3">
    <div class="flex flex-col rounded-3xl bg-gray-800 bg-opacity-40 py-2 px-4 md:px-24 lg:px-48 drop-shadow-2xl backdrop-blur-2xl mt-10 h-full">
      <h1 class=" absolute top-5 left-10 font-sans1  text-black text-2xl text-semibold md:text-4xl hover:text-white bg-cyan-400 rounded-full px-4 py-1">
        Conversations
      </h1>
      <div id="chat-container" class="flex flex-col h-screen overflow-y-auto">
        <div id="chat-response" class="flex-1 overflow-y-auto px-4 py-6 sm:px-16"></div>
      </div>
      <div class="flex flex-row space-x-6">
        <a href="{% url 'chat:chat' %}"
           class="w-full mb-4 py-2 font-sans1 flex items-center justify-between px-4 bg-gray-800 bg-opacity-60 backdrop-blur-xl hover:bg-gradient-to-r hover:from-cyan-300 hover:to-blue-500 hover:text-black text-white rounded-full">
          <div class="flex-grow"></div>
          <p class="text-center flex-shrink-0">Chat</p>
          <div class="flex-grow flex justify-end">
            <svg width="20px"
                 height="20px"
                 viewBox="0 -1 25 25"
                 fill="none"
                 xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M18.455 9.8834L7.063 4.1434C6.76535 3.96928 6.40109 3.95274 6.08888 4.09916C5.77667 4.24558 5.55647 4.53621 5.5 4.8764C5.5039 4.98942 5.53114 5.10041 5.58 5.2024L7.749 10.4424C7.85786 10.7903 7.91711 11.1519 7.925 11.5164C7.91714 11.8809 7.85789 12.2425 7.749 12.5904L5.58 17.8304C5.53114 17.9324 5.5039 18.0434 5.5 18.1564C5.55687 18.4961 5.77703 18.7862 6.0889 18.9323C6.40078 19.0785 6.76456 19.062 7.062 18.8884L18.455 13.1484C19.0903 12.8533 19.4967 12.2164 19.4967 11.5159C19.4967 10.8154 19.0903 10.1785 18.455 9.8834V9.8834Z" stroke="#FFFFFF" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          </div>
        </a>
      </div>
    </div>
  </div>
{% endblock content %}

llm_on_web/templates/users/conversations_detailed.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  Conversations
{% endblock title %}
{% block bodyclass %}
  bg-gemma bg-cover bg-no-repeat min-h-screen overflow-hidden
{% endblock bodyclass %}
{% block javascript %}
  {{ block.super }}
  <script src="{% static 'js/chat-handle.js' %}"></script>
{% endblock javascript %}
{% block content %}
  <div class="h-custom-vh w-full mt-20 px-3">
    <div class="flex flex-col rounded-3xl bg-gray-800 bg-opacity-40 py-2 px-4 md:px-24 lg:px-48 drop-shadow-2xl backdrop-blur-2xl mt-10 h-full">
      <h1 class="absolute top-5 left-10 font-sans1 text-black text-2xl font-semibold md:text-4xl hover:text-white bg-cyan-400 rounded-full px-4 py-1">
        Conversations
      </h1>
      <div id="chat-container" class="flex flex-col h-screen overflow-y-auto">
        <div id="chat-response" class="flex-1 overflow-y-auto px-4 py-6 sm:px-16">
          {% if request.user.is_authenticated %}
            {% for conversation in user_conversations %}
              <div class="flex justify-end">
                <div class="flex bg-opacity-30 mt-14 bg-gray-800 text-white mb-2 font-sans1 rounded-xl break-words py-2 px-4 max-w-sm outline outline-offset-2 outline-blue-500">
                  {{ conversation.user_query }}
                  {% if conversation.imagequery %}
                    <img class="size-40 mt-4"
                         src="{% get_media_prefix %}{{ conversation.imagequery }}"
                         alt="userqueryimage" />
                  {% endif %}
                </div>
              </div>
              <div class="flex justify-start">
                <div class="bg-opacity-30 mt-4 mb-2 bg-gray-800 text-white font-sans1 break-words rounded-lg py-2 px-4 max-w-sm outline outline-offset-2 outline-cyan-500">
                  {{ conversation.llm_response }}
                </div>
              </div>
            {% endfor %}
          {% else %}
            <p>Please log in to view your conversations.</p>
          {% endif %}
        </div>
      </div>
      <div class="flex flex-row space-x-6">
        <a href="{% url 'chat:chat' %}"
           class="w-full mb-4 py-2 font-sans1 flex items-center justify-between px-4 bg-gray-800 bg-opacity-60 backdrop-blur-xl hover:bg-gradient-to-r hover:from-cyan-300 hover:to-blue-500 hover:text-black text-white rounded-full">
          <div class="flex-grow"></div>
          <p class="text-center flex-shrink-0">Chat</p>
          <div class="flex-grow flex justify-end">
            <svg width="20px"
                 height="20px"
                 viewBox="0 -1 25 25"
                 fill="none"
                 xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M18.455 9.8834L7.063 4.1434C6.76535 3.96928 6.40109 3.95274 6.08888 4.09916C5.77667 4.24558 5.55647 4.53621 5.5 4.8764C5.5039 4.98942 5.53114 5.10041 5.58 5.2024L7.749 10.4424C7.85786 10.7903 7.91711 11.1519 7.925 11.5164C7.91714 11.8809 7.85789 12.2425 7.749 12.5904L5.58 17.8304C5.53114 17.9324 5.5039 18.0434 5.5 18.1564C5.55687 18.4961 5.77703 18.7862 6.0889 18.9323C6.40078 19.0785 6.76456 19.062 7.062 18.8884L18.455 13.1484C19.0903 12.8533 19.4967 12.2164 19.4967 11.5159C19.4967 10.8154 19.0903 10.1785 18.455 9.8834V9.8834Z" stroke="#FFFFFF" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          </div>
        </a>
      </div>
    </div>
  </div>
{% endblock content %}

llm_on_web/templates/users/user_detail.html
{% extends "base.html" %}

{% load static %}
{% load allauth account %}

{% block title %}
  Profile
{% endblock title %}
{% block bodyclass %}
  bg-gemma bg-cover   bg-opacity-20 bg-no-repeat min-h-screen
{% endblock bodyclass %}
{% block content %}
  <div class="hidden lg:flex -z-50 h-screen w-screen justify-center items-center font-sans1">
    <div class="rounded-3xl bg-gray-800 bg-opacity-40 px-10 py-10 mt-16 shadow-2xl backdrop-blur-md">
      <div class="mx-auto w-40 h-40 mb-8">
        <img class="bg-cover bg-center w-full h-full rounded-full drop-shadow-2xl"
             src="{% if object.userpicture %}/media/{{ object.userpicture }}{% else %}{% static 'images/user1.svg' %}{% endif %}"
             alt="User Picture" />
      </div>
      <div class="relative left-26 top-0 mb-8">
        <h1 class="VK-Sans text-center mt-9  text-6xl mb-8 bg-cyan-400 rounded-full text-gray-800 font-sans1 px-4 py-2">
          Profile
        </h1>
      </div>
      <div class="flex flex-row py-8 items-center justify-center">
        <div class="flex flex-col space-y-14">
          <div class="flex flex-row space-x-14 items-center justify-center">
            <p class="text-center text-xl text-white font-sans1">Name</p>
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="94"
                 height="32"
                 viewBox="0 0 94 32"
                 fill="none">
              <path d="M77 1L93 16L77 31" stroke="white" />
              <path d="M93 16L0 16" stroke="white" />
            </svg>
          </div>
          <div class="flex flex-row space-x-14 items-center justify-center">
            <p class="text-center text-xl text-white font-sans1">Email</p>
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="94"
                 height="32"
                 viewBox="0 0 94 32"
                 fill="none">
              <path d="M77 1L93 16L77 31" stroke="white" />
              <path d="M93 16L0 16" stroke="white" />
            </svg>
          </div>
        </div>
        <div class="flex flex-col ml-8 space-y-10">
          <div class=" mt-1 mb-1  text-white bg-gray-800 bg-opacity-20 font-sans1 border border-gray-200 rounded-full text-md px-10 py-2 text-center  items-center">
            {% if object.name %}
              {{ object.name }}
            {% else %}
              Add your name in the settings
            {% endif %}
          </div>
          <div class="mt-1 mb-1   text-white bg-gray-800 bg-opacity-20 font-sans1  border border-gray-200  rounded-full text-md px-10 py-2 text-center items-center">
            {{ object.email }}
          </div>
        </div>
      </div>
      <div class="flex flex-row py-6  space-x-12 items-center justify-center">
        {% if object == request.user %}
          <a href="{% url 'users:update' %}"
             role="button"
             class="mt-1 mb-1   text-white bg-gray-800 bg-opacity-20   font-sans1 border border-gray-200  rounded-full text-md px-10 py-2  text-center items-center">
            Edit your profile
          </a>
        {% else %}
          <div class="mt-1 mb-1   text-white bg-gray-800 bg-opacity-20 font-sans1   border border-gray-200  rounded-full text-md px-10 py-2  text-center items-center">
            You are not authorized
          </div>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="lg:hidden flex h-screen w-screen flex-col justify-center items-center">
    <div class="rounded-3xl bg-gray-800 bg-opacity-40 px-20 py-10 shadow-2xl backdrop-blur-md">
      <div class="relative">
        <img class="bg-cover bg-center w-36 h-36 md:w-48 md:h-48 rounded-full mx-auto mb-4"
             src=" {% if object.userpicture %}/media/{{ object.userpicture }}{% else %}{% static 'images/user1.svg' %}{% endif %}"
             alt="user-picture" />
        <h1 class="text-center mt-4 text-3xl text-white font-sans1  md:text-3xl mb-4">Profile</h1>
        <h1 class="text-center mt-4 mb-4 text-sm sm:text-md font-sans1 text-white ">Here are your details!</h1>
      </div>
      <div class="flex flex-col space-y-4">
        <div class="text-white bg-gray-800 bg-opacity-20 border border-gray-200 rounded-full text-md font-sans1 px-6 py-2 text-center">
          {% if object.name %}
            {{ object.name }}
          {% else %}
            Add your name in the settings
          {% endif %}
        </div>
        <div class=" text-white bg-gray-800 bg-opacity-20 border border-gray-200 rounded-full font-sans1 text-md px-6 py-2 text-center">
          Email: {{ object.email }}
        </div>
        <a href="{% url 'users:update' %}"
           class=" text-white bg-gray-800 bg-opacity-20 border border-gray-200 rounded-full  font-sans1 text-md px-6 py-2 text-center">
          Click here to edit
        </a>
      </div>
    </div>
  </div>
{% endblock content %}