config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token
from llm_on_web.users.views import user_contact_view

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    path("chat/", include("llm_on_web.chat.urls"), name="chat"),
    path(
        "contact/",
        view=user_contact_view,
        name="contact",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("llm_on_web.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

llm_on_web/chat/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import llava_chat_view
from .views import user_chat_view

app_name = "chat"
urlpatterns = [
    path("", view=user_chat_view, name="chat"),
    path(
        "llava/",
        view=llava_chat_view,
        name="llava",
    ),
    path(
        "llava/conversations/",
        TemplateView.as_view(template_name="pages/chat_llava.html"),
        name="llava_conversation",
    ),
]

llm_on_web/users/urls.py
from django.urls import path

from .views import user_conversations_detailed_view
from .views import user_conversations_view
from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
    path("<int:pk>/conversations/", view=user_conversations_view, name="conversations"),
    path(
        "conversations/<uuid:conversationid>/",
        view=user_conversations_detailed_view,
        name="conversation_detail",
    ),
]

llm_on_web/chat/models.py
import uuid

from django.db import models

from llm_on_web.users.models import User


class Chatid(models.Model):
    chatid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    chat_title = models.CharField(max_length=255, default="", blank=True)
    userid = models.ForeignKey(User, on_delete=models.RESTRICT, null=True)

    def __str__(self):
        return f"Chats: {self.userid}"


class Conversations(models.Model):
    conversationid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    chatid = models.ForeignKey(
        Chatid,
        on_delete=models.CASCADE,
        related_name="conversations",
    )
    userid = models.ForeignKey(User, on_delete=models.RESTRICT)
    llm_response = models.TextField(max_length=1000, default="", blank=True)
    user_query = models.TextField(default="")
    imagequery = models.ImageField(
        upload_to="user-images-query/",
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (
            f"Conversation {self.conversationid} in chat {self.chatid} by {self.userid}"
        )

llm_on_web/users/models.py
from typing import ClassVar

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import CharField
from django.db.models import EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .managers import UserManager


class User(AbstractUser):
    """
    Default custom user model for llm_on_web.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore[assignment]
    last_name = None  # type: ignore[assignment]
    email = EmailField(_("email address"), unique=True)
    username = None  # type: ignore[assignment]
    userpicture = models.ImageField(upload_to="user_pictures/", blank=True, null=True)
    currentchatid = models.CharField(default="", blank=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects: ClassVar[UserManager] = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

llm_on_web/chat/forms.py
from llm_on_web.chat.models import Conversations


class UserConversationForm:
    class Meta:
        model = Conversations
        fields = ["userid", "user_query", "imagequery"]

llm_on_web/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django import forms
from django.contrib.auth import forms as admin_forms
from django.core.validators import EmailValidator
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):  # type: ignore[name-defined]
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):  # type: ignore[name-defined]
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["name", "email", "userpicture"]


class UserContactForm(forms.Form):
    email = forms.CharField(validators=[EmailValidator()])
    subject = forms.CharField(max_length=255)
    message = forms.CharField(widget=forms.Textarea)

llm_on_web/chat/views.py
from datetime import datetime

import pytz
from django.shortcuts import render
from django.views.generic import TemplateView

from llm_on_web.users.models import User

from .models import Chatid


class ChatMixin:
    def handle_authenticated_user(self, request):
        current_user = User.objects.get(pk=request.user.pk)
        chat_title = str(datetime.now(pytz.utc))
        newchat = Chatid.objects.create(chat_title=chat_title)
        newchat.userid = current_user
        newchat.save()
        current_chat_id = newchat.chatid
        current_user.currentchatid = current_chat_id
        current_user.save()


class ChatView(ChatMixin, TemplateView):
    template_name = "pages/chat.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.handle_authenticated_user(request)
        return render(request, self.template_name)


user_chat_view = ChatView.as_view()


class LlavaChatView(ChatMixin, TemplateView):
    template_name = "pages/chat_llava.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.handle_authenticated_user(request)
        return render(request, self.template_name)


llava_chat_view = LlavaChatView.as_view()

llm_on_web/users/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin
from rest_framework.mixins import RetrieveModelMixin
from rest_framework.mixins import UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from llm_on_web.users.models import User

from .serializers import UserSerializer


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "pk"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

llm_on_web/users/views.py
# ruff: noqa: E501

from allauth.account.models import EmailAddress
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import EmailMessage
from django.core.mail import get_connection
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import FormView
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.views.generic import UpdateView

from config.settings.local import RESEND_API_KEY
from config.settings.local import RESEND_SMTP_HOST
from config.settings.local import RESEND_SMTP_PORT
from config.settings.local import RESEND_SMTP_USERNAME
from llm_on_web.chat.models import Chatid
from llm_on_web.chat.models import Conversations
from llm_on_web.users.forms import UserContactForm
from llm_on_web.users.forms import UserUpdateForm
from llm_on_web.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = UserUpdateForm
    template_name = "users/user_form.html"
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        response = super().form_valid(form)
        new_email = form.cleaned_data.get("email")
        email_address = EmailAddress.objects.filter(user=self.object).first()
        if email_address:
            email_address.email = new_email
            email_address.save()
        else:
            EmailAddress.objects.create(
                user=self.object,
                email=new_email,
                verified=True,
                primary=True,
            )
        return response


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()


class UserConversationsView(LoginRequiredMixin, TemplateView):
    template_name = "users/conversations.html"

    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=request.user.pk)
        user_chats = Chatid.objects.filter(userid=user)
        conversations_with_chatid = (
            Conversations.objects.filter(chatid__in=user_chats)
            .select_related("chatid")
            .all()
        )
        unique_chatids = {
            conversation.chatid for conversation in conversations_with_chatid
        }
        context = {"chats": unique_chatids}
        return render(request, template_name=self.template_name, context=context)


user_conversations_view = UserConversationsView.as_view()


class UserConversationsDetailedView(LoginRequiredMixin, TemplateView):
    template_name = "users/conversations_detailed.html"  # corrected the conversations

    def get(self, request, *args, **kwargs):
        queridtid = kwargs.get("conversationid")
        chatid = get_object_or_404(Chatid, chatid=queridtid)
        user_conversations = Conversations.objects.filter(chatid=chatid)
        context = {"user_conversations": user_conversations}
        return self.render_to_response(context)


user_conversations_detailed_view = UserConversationsDetailedView.as_view()


class UserContactView(LoginRequiredMixin, FormView):
    template_name = "pages/contact.html"
    form_class = UserContactForm
    success_url = "/contact"

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        subject = form.cleaned_data["subject"]
        message = form.cleaned_data["message"]
        from_email = "gemma_support@appsupport.shukla.ru"
        body1 = "Thank you for contacting us"
        body2 = f"we got the following message: {message}"

        if form.is_valid():
            with get_connection(
                host=RESEND_SMTP_HOST,
                port=RESEND_SMTP_PORT,
                username=RESEND_SMTP_USERNAME,
                password=RESEND_API_KEY,
                use_tls=True,
            ) as connection:
                EmailMessage(
                    subject=subject,
                    body=body1 + body2,
                    to=[email],
                    from_email=from_email,
                    connection=connection,
                ).send(fail_silently=False)

            return super().form_valid(form)

        return redirect("contact")


user_contact_view = UserContactView.as_view()

llm_on_web/templates/pages/about.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  About
{% endblock title %}
{% block bodyclass %}
  bg-gemma bg-cover bg-no-repeat overflow-hidden
{% endblock bodyclass %}
{% block javascript %}
  <script type="importmap">
    {
      "imports": {
        "three": "https://cdn.jsdelivr.net/npm/three@0.165.0/build/three.module.js",
        "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.165.0/examples/jsm/"
      }
    }
  </script>
  <script src="{% static 'js/project.js/' %}" type="module"></script>
{% endblock javascript %}
{% block content %}
  <div class="flex flex-col items-center justify-center">
    <canvas class="flex flex-col h-[50px] w-[300px] items-center justify-center">
    </canvas>
    <p class="flex mt-14 mb-8 text-2xl text-bold text-white text-center sm:text-6xl font-cassa">We @Gemma, hire llamas</p>
    <p class="flex mt-4 mb-8 text-2xl text-bold text-white text-center sm:text-6xl font-cassa">
      and then use the LLM models that they create
    </p>
    <p class="flex mt-4  font-extrabold text-white text-center sm:text-lg font-cassa">ps. here is a 3d llama for you</p>
  </div>
{% endblock content %}

llm_on_web/templates/pages/chat_llava.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  Chat - LLava
{% endblock title %}
{% block bodyclass %}
 bg-gemma bg-cover bg-no-repeat min-h-screen overflow-hidden
{% endblock bodyclass %}
{% block inline_javascript %}
  <script src="{% static 'js/chat-llava-handle.js' %}"  type="module"></script>
{% endblock inline_javascript %}
{% block content %}
  <div class="h-custom-vh w-full py-10  max-sm:py-12  px-3  overflow-y-clip appearance-none ">
    <div class="flex flex-col rounded-3xl bg-gray-800 bg-opacity-40 py-2 px-4 md:px-24 lg:px-48 drop-shadow-2xl backdrop-blur-2xl mt-10 h-full">
      <h1 class=" absolute top-30 left-10 font-sans1  text-black text-3xl text-semibold md:text-4xl hover:text-white bg-cyan-400 rounded-full px-4 py-1">
        Chat
      </h1>
      <a href="{% url 'chat:llava' %}" class=" absolute top-30 right-10">
        <svg width="40px"
             height="45px"
             viewBox="0 0 24 24"
             fill="#FFFFFF"
             xmlns="http://www.w3.org/2000/svg"
             stroke-width="1">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M12 3C7.85113 3 4 5.73396 4 10C4 11.5704 4.38842 12.7289 5.08252 13.6554C5.79003 14.5998 6.87746 15.3863 8.41627 16.0908L9.2326 16.4645L8.94868 17.3162C8.54129 18.5384 7.84997 19.6611 7.15156 20.5844C9.56467 19.8263 12.7167 18.6537 14.9453 17.1679C17.1551 15.6948 18.3969 14.5353 19.0991 13.455C19.7758 12.4139 20 11.371 20 10C20 5.73396 16.1489 3 12 3ZM2 10C2 4.26604 7.14887 1 12 1C16.8511 1 22 4.26604 22 10C22 11.629 21.7242 13.0861 20.7759 14.545C19.8531 15.9647 18.3449 17.3052 16.0547 18.8321C13.0781 20.8164 8.76589 22.2232 6.29772 22.9281C5.48665 23.1597 4.84055 22.6838 4.56243 22.1881C4.28848 21.6998 4.22087 20.9454 4.74413 20.3614C5.44439 19.5798 6.21203 18.5732 6.72616 17.4871C5.40034 16.7841 4.29326 15.9376 3.48189 14.8545C2.48785 13.5277 2 11.9296 2 10Z" fill="#FFFFFF" />
          <path d="M12 6C11.4477 6 11 6.44771 11 7V9H9C8.44772 9 8 9.44771 8 10C8 10.5523 8.44772 11 9 11H11V13C11 13.5523 11.4477 14 12 14C12.5523 14 13 13.5523 13 13V11H15C15.5523 11 16 10.5523 16 10C16 9.44772 15.5523 9 15 9H13V7C13 6.44771 12.5523 6 12 6Z" fill="#FFFFFF" />
        </svg>
      </a>
      <div id="chat-container"
           class="flex mt-10 flex-col h-screen overflow-y-auto">
        <div id="chat-response"
             class="mt-4 flex-1 overflow-y-auto px-4 py-6 sm:px-16"></div>
      </div>
      <div class="flex flex-row space-x-6">
        <button id="dropdownDefaultButton"
                data-dropdown-toggle="dropdown"
                data-dropdown-placement="top"
                class="text-white mb-4 "
                type="button">
          <svg class=" h-2.5 "
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
          </svg>
        </button>
        <div id="dropdown"
             class="hidden  divide-y divide-gray-800  rounded-full shadow-full  w-44 bg-gray-700">
          <ul class="py-2 text-sm text-gray-200 rounded-full"
              aria-labelledby="dropdownDefaultButton">
            <li>
              <a href="{% url 'chat:chat' %}"
                 class="block px-4 rounded-full bg-gray-800 bg-opacity-20 text-white  fonst-sans1">Model: llama</a>
            </li>
          </ul>
        </div>
        <form action="{% url 'chat:llava_conversation' %}"
              class="flex flex-row  w-screen"
              id="user_image_form"
              name="user_image_form">
          {% csrf_token %}
          <label class="block relative left-10 cursor-pointer  top-3 sm:top-2 z-50 h-4 w-8"
                 for="multiple_files">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 38 38" id="paperclip">
              <path d="M23.113 7.248h-0.002c0 0 0 0 0 0-0.689 0-1.248 0.558-1.25 1.247v0l-0.029 14.198c0.008 0.114 0.013 0.247 0.013 0.381 0 3.118-2.528 5.646-5.646 5.646-0.071 0-0.142-0.001-0.212-0.004l0.010 0h-0.014c-0.063 0.003-0.138 0.004-0.213 0.004-3.117 0-5.643-2.527-5.643-5.643 0-0.126 0.004-0.25 0.012-0.374l-0.001 0.017v-15.516c-0.004-0.063-0.006-0.136-0.006-0.21 0-2.054 1.665-3.719 3.719-3.719 0.074 0 0.147 0.002 0.219 0.006l-0.010-0c0.063-0.004 0.136-0.006 0.21-0.006 2.053 0 3.717 1.664 3.717 3.717 0 0.073-0.002 0.145-0.006 0.217l0-0.010-0.057 14.272c0.002 0.045 0.004 0.097 0.004 0.15 0 0.719-0.259 1.378-0.689 1.887l0.004-0.004c-0.332 0.333-0.788 0.544-1.293 0.557l-0.002 0c-0.51-0.006-0.966-0.228-1.284-0.578l-0.001-0.002c-0.407-0.5-0.654-1.145-0.654-1.847 0-0.073 0.003-0.145 0.008-0.217l-0.001 0.010v-10.344c0-0.69-0.56-1.25-1.25-1.25s-1.25 0.56-1.25 1.25v0 10.332c-0.018 0.153-0.028 0.33-0.028 0.51 0 2.491 1.964 4.524 4.428 4.634l0.010 0 0.038 0.002c0.003 0 0.006 0 0.009 0 1.214 0 2.308-0.512 3.078-1.332l0.002-0.002c0.852-0.937 1.374-2.189 1.374-3.561 0-0.062-0.001-0.124-0.003-0.186l0 0.009 0.057-14.285c0-8.434-12.844-8.434-12.844 0v15.518c-0.003 0.083-0.005 0.18-0.005 0.277 0 2.4 1.015 4.564 2.64 6.084l0.005 0.004c1.485 1.322 3.452 2.129 5.608 2.129 0.034 0 0.068-0 0.102-0.001l-0.005 0h0.019c0.025 0 0.054 0 0.083 0 2.168 0 4.146-0.817 5.642-2.16l-0.008 0.007c1.614-1.523 2.619-3.676 2.619-6.064 0-0.108-0.002-0.215-0.006-0.322l0 0.015 0.029-14.192c0-0.001 0-0.002 0-0.004 0-0.69-0.559-1.249-1.248-1.249h-0z" fill="#FFFFFF" />
            </svg>
          </label>
          <input class="hidden absolute "
                 id="multiple_files"
                 type="file"
                 name="imagequery" required />
          <img id="preview"
               class=" hidden absolute rounded-lg  h-28 w-28 bottom-28 max-h[100px] max-w[100px]"
               alt="preview of user image" />
          <input class="w-full mb-4 pl-14 py-2 px-4 bg-gray-800 bg-opacity-70 backdrop-blur-xl  text-white rounded-full"
                 name="user_query"
                 id="user_query"
                 placeholder="Ask something..." required/>
          <input class="hidden"
                 name="who"
                 id="who"
                 value="{% if request.user.is_authenticated %} {{ request.user.pk }} {% else %}guest{% endif %} " />
          <button id="form-submit"
                  type="submit"
                  name="submit"
                  class="mb-4 ml-2 bg-opacity-70 bg-gray-800 backdrop-blur-xl rounded-full  hover:bg-gradient-to-r hover:from-cyan-300 hover:to-blue-500 ">
            <svg width="40px"
                 height="35px"
                 viewBox="0 -1 25 25"
                 fill="none"
                 xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M18.455 9.8834L7.063 4.1434C6.76535 3.96928 6.40109 3.95274 6.08888 4.09916C5.77667 4.24558 5.55647 4.53621 5.5 4.8764C5.5039 4.98942 5.53114 5.10041 5.58 5.2024L7.749 10.4424C7.85786 10.7903 7.91711 11.1519 7.925 11.5164C7.91714 11.8809 7.85789 12.2425 7.749 12.5904L5.58 17.8304C5.53114 17.9324 5.5039 18.0434 5.5 18.1564C5.55687 18.4961 5.77703 18.7862 6.0889 18.9323C6.40078 19.0785 6.76456 19.062 7.062 18.8884L18.455 13.1484C19.0903 12.8533 19.4967 12.2164 19.4967 11.5159C19.4967 10.8154 19.0903 10.1785 18.455 9.8834V9.8834Z" stroke="#FFFFFF" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          </button>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

llm_on_web/templates/pages/home.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  Home
{% endblock title %}
{% block bodyclass %}
  bg-gemma bg-cover bg-no-repeat min-w-screen min-h-screen overflow-hidden
{% endblock bodyclass %}
{% block content %}
  {% block javascript %}
    {{ block.super }}
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        gsap.to("#mainText", {
          duration: 1,
          text: "Try LLMs locally!",
          delay: 1,
        });
      });
    </script>
  {% endblock javascript %}
  <div class="flex flex-row justify-center mt-40">
    <div class="items-center drop-shadow-2xl">
      <img src="{% static 'images/gemini-icon.png' %}"
           alt="Gemma"
           width="300"
           height="300" />
    </div>
    <div class="hidden sm:block ">
      <img class="drop-shadow-lg"
           src="{% static 'images/gemini-icon.png' %}"
           alt="Gemma"
           width="200"
           height="200" />
    </div>
  </div>
  <div class="flex justify-center ml-10 mt-20 ">
    <h1 id="mainText"
        class="lg:text-8xl  text-3xl text-center text-white font-sans1">Welcome to Gemma!</h1>
  </div>
{% endblock content %}